Startup Profit Prediction Using Regression

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [ ]:
stup=pd.read_csv("50_Startups.csv")

In [ ]:
stup.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
x = stup.iloc[: , :-1].values

y = stup.iloc[: , -1].values

In [ ]:
from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import OneHotEncoder

ct  = ColumnTransformer(transformers = [('encoder', OneHotEncoder() , [3])], remainder = 'passthrough')

x = np.array(ct.fit_transform(x))
print(x)


[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(
		x, y, test_size = 0.3, random_state = 0)
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
lm.fit(x_train, y_train)
pred = lm.predict(x_test)
print(pred.reshape(15,1))


[[104282.76]
 [132536.88]
 [133910.85]
 [ 72584.77]
 [179920.93]
 [114549.31]
 [ 66444.43]
 [ 98404.97]
 [114499.83]
 [169367.51]
 [ 96522.63]
 [ 88040.67]
 [110949.99]
 [ 90419.19]
 [128020.46]]


In [ ]:
y_pred = lm.predict(x_test)

np.set_printoptions(precision=2)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[104282.76 103282.38]
 [132536.88 144259.4 ]
 [133910.85 146121.95]
 [ 72584.77  77798.83]
 [179920.93 191050.39]
 [114549.31 105008.31]
 [ 66444.43  81229.06]
 [ 98404.97  97483.56]
 [114499.83 110352.25]
 [169367.51 166187.94]
 [ 96522.63  96778.92]
 [ 88040.67  96479.51]
 [110949.99 105733.54]
 [ 90419.19  96712.8 ]
 [128020.46 124266.9 ]]
