TARGET ADVERTISING USING CLASSIFICATION ALGO


In [21]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns

In [22]:
df = pd.read_csv('Social_Network_Ads.csv')


In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [24]:
df.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [25]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [26]:
X = df.iloc[:,:-1]
Y = df['Purchased']

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [28]:
from sklearn.preprocessing import StandardScaler
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

TRAINING MODELS AND PREDICTING RESULTS WITH ACCURACY SCORE AND CONFUSION MATRIX

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB 
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
import warnings
warnings.filterwarnings("ignore")

#*******************Score Header Files******************
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix

In [30]:
log_clf = LogisticRegression()
nbg_clf = GaussianNB()
rnd_clf = RandomForestClassifier()
svm_clf = SVC()
det_clf = DecisionTreeClassifier()
knn_clf = KNeighborsClassifier(n_neighbors=2)
svm_poly_clf = SVC(kernel='poly')
svm_lin_clf = SVC(kernel='linear')

for clf in (log_clf, knn_clf, svm_lin_clf, svm_clf, svm_poly_clf, nbg_clf, det_clf, rnd_clf):
    clf.fit(X_train, y_train)
    
    y_pred = clf.predict(X_test)
    
    print(clf.__class__.__name__)
    print('Accuracy: ',accuracy_score(y_test, y_pred))
    print('Confusion Matrix: \n',confusion_matrix(y_test,y_pred))
    print(' ')

LogisticRegression
Accuracy:  0.8875
Confusion Matrix: 
 [[52  6]
 [ 3 19]]
 
KNeighborsClassifier
Accuracy:  0.925
Confusion Matrix: 
 [[56  2]
 [ 4 18]]
 
SVC
Accuracy:  0.8875
Confusion Matrix: 
 [[52  6]
 [ 3 19]]
 
SVC
Accuracy:  0.9375
Confusion Matrix: 
 [[54  4]
 [ 1 21]]
 
SVC
Accuracy:  0.9
Confusion Matrix: 
 [[55  3]
 [ 5 17]]
 
GaussianNB
Accuracy:  0.9375
Confusion Matrix: 
 [[54  4]
 [ 1 21]]
 
DecisionTreeClassifier
Accuracy:  0.9125
Confusion Matrix: 
 [[53  5]
 [ 2 20]]
 
RandomForestClassifier
Accuracy:  0.925
Confusion Matrix: 
 [[53  5]
 [ 1 21]]
 


MODEL WITH HIGHEST ACCURACY - Gaussian Naive Bayes